export const CS_PRESETS = [
  "Algorithms", "Data Structures", "Computer Architecture", "Machine Learning",
  "Artificial Intelligence", "Operating Systems", "Networking", "Database Systems",
  "Cryptography", "Cybersecurity", "Software Engineering", "Compiler Design",
  "Distributed Systems", "Cloud Computing", "Parallel Computing", "Quantum Computing",
  "Computer Graphics", "Human-Computer Interaction", "Computer Vision", "Natural Language Processing",
  "Discrete Mathematics", "Theory of Computation", "Information Theory", "Automata Theory",
  "Information Retrieval", "Data Mining", "Big Data", "Bioinformatics",
  "Computer Ethics", "Microprocessors", "Digital Logic", "Embedded Systems",
  "VLSI Design", "Computer Organization", "Assembly Language", "Instruction Set Architecture",
  "Pipelining", "Cache Memory", "Virtual Memory", "Multithreading",
  "Concurrency", "Network Protocols", "TCP/IP", "Routing Algorithms",
  "Wireless Networks", "Network Security", "Relational Databases", "NoSQL",
  "SQL", "Transaction Processing", "Object-Oriented Programming", "Functional Programming",
  "Version Control", "Agile Software Development", "DevOps", "Continuous Integration",
  "Software Testing", "Microservices", "RESTful APIs", "GraphQL",
  "Containerization", "Docker", "Kubernetes", "Serverless Computing",
  "Blockchain", "Smart Contracts", "IoT", "Robotics",
  "Deep Learning", "Neural Networks", "Reinforcement Learning", "Generative AI",
  "Transformers", "Computer Animation", "Virtual Reality", "Augmented Reality",
  "Symmetric-Key Cryptography", "Public-Key Cryptography", "Hash Functions", "Digital Signatures",
  "Malware Analysis", "Penetration Testing", "Firewalls", "Intrusion Detection Systems",
  "Graph Theory", "Linear Algebra", "Calculus", "Probability Theory",
  "Statistics", "Optimization", "Turing Machine", "Complexity Classes",
  "P vs NP", "Algorithm Analysis", "Big O Notation", "Sorting Algorithms",
  "Search Algorithms", "Dynamic Programming", "Greedy Algorithms", "Graph Algorithms"
];
